-- Seed data: major conservative organizations and relationships

INSERT INTO organizations (name, category, description, website, state, city, annual_revenue, verified) VALUES
  ('Republican National Committee', 'National Party Committee', 'The main organizational body of the Republican Party', 'https://www.gop.com', 'DC', 'Washington', 300000000, true),
  ('Heritage Foundation', 'Think Tank', 'Conservative think tank and policy research organization. Publishes the annual Mandate for Leadership and created Project 2025.', 'https://www.heritage.org', 'DC', 'Washington', 86000000, true),
  ('American Enterprise Institute', 'Think Tank', 'Center-right think tank focused on government, economics, and foreign policy', 'https://www.aei.org', 'DC', 'Washington', 55000000, true),
  ('Federalist Society', '501(c)(3) Nonprofit', 'Organization of conservatives and libertarians focused on reforming the legal system. Major influence on judicial nominations.', 'https://fedsoc.org', 'DC', 'Washington', 25000000, true),
  ('Americans for Prosperity', '501(c)(4) Nonprofit', 'Koch-network advocacy group focused on free-market policies', 'https://americansforprosperity.org', 'VA', 'Arlington', 60000000, true),
  ('Club for Growth', 'PAC', 'Fiscally conservative PAC that supports pro-growth candidates', 'https://www.clubforgrowth.org', 'DC', 'Washington', 30000000, true),
  ('National Rifle Association', '501(c)(4) Nonprofit', 'Gun rights advocacy organization', 'https://www.nra.org', 'VA', 'Fairfax', 250000000, true),
  ('Turning Point USA', '501(c)(3) Nonprofit', 'Conservative youth organization focused on college campuses', 'https://www.tpusa.com', 'AZ', 'Phoenix', 80000000, true),
  ('Susan B. Anthony Pro-Life America', 'PAC', 'Anti-abortion political organization', 'https://sbaprolife.org', 'VA', 'Arlington', 18000000, true),
  ('Judicial Watch', '501(c)(3) Nonprofit', 'Conservative legal watchdog organization using FOIA requests', 'https://www.judicialwatch.org', 'DC', 'Washington', 50000000, true),
  ('Faith & Freedom Coalition', '501(c)(4) Nonprofit', 'Christian conservative advocacy organization founded by Ralph Reed', 'https://www.ffcoalition.com', 'GA', 'Duluth', 15000000, true),
  ('American Conservative Union', '501(c)(4) Nonprofit', 'Hosts CPAC (Conservative Political Action Conference)', 'https://conservative.org', 'VA', 'Alexandria', 20000000, true),
  ('The Daily Wire', 'Media Organization', 'Conservative media company founded by Ben Shapiro', 'https://www.dailywire.com', 'TN', 'Nashville', 100000000, true),
  ('Fox News', 'Media Organization', 'Conservative cable news network (Fox Corporation subsidiary)', 'https://www.foxnews.com', 'NY', 'New York', 3000000000, true),
  ('Hillsdale College', '501(c)(3) Nonprofit', 'Conservative liberal arts college; influential in right-wing education policy', 'https://www.hillsdale.edu', 'MI', 'Hillsdale', 120000000, true),
  ('Leadership Institute', '501(c)(3) Nonprofit', 'Conservative training organization for political activists and campaign staff', 'https://www.leadershipinstitute.org', 'VA', 'Arlington', 17000000, true),
  ('Senate Leadership Fund', 'Super PAC', 'McConnell-aligned Super PAC supporting Republican Senate candidates', NULL, 'DC', 'Washington', 230000000, true),
  ('Congressional Leadership Fund', 'Super PAC', 'Super PAC supporting Republican House candidates', NULL, 'DC', 'Washington', 200000000, true),
  ('Koch Industries', 'Business / Corporation', 'Conglomerate; Koch network is major funder of conservative causes', 'https://www.kochind.com', 'KS', 'Wichita', 125000000000, true),
  ('Alliance Defending Freedom', '501(c)(3) Nonprofit', 'Conservative Christian legal advocacy organization', 'https://adflegal.org', 'AZ', 'Scottsdale', 90000000, true),
  ('Cato Institute', 'Think Tank', 'Libertarian think tank focused on individual liberty and free markets', 'https://www.cato.org', 'DC', 'Washington', 40000000, true),
  ('Manhattan Institute', 'Think Tank', 'Conservative think tank focused on urban policy and economic growth', 'https://www.manhattan-institute.org', 'NY', 'New York', 15000000, true),
  ('PragerU', 'Media Organization', 'Conservative media nonprofit producing short educational videos', 'https://www.prageru.com', 'CA', 'Los Angeles', 50000000, true),
  ('Family Research Council', '501(c)(4) Nonprofit', 'Conservative Christian advocacy group focused on family values', 'https://www.frc.org', 'DC', 'Washington', 18000000, true),
  ('Competitive Enterprise Institute', 'Think Tank', 'Libertarian think tank focused on deregulation and free enterprise', 'https://cei.org', 'DC', 'Washington', 8000000, true),
  ('Pacific Legal Foundation', '501(c)(3) Nonprofit', 'Public interest law firm advancing property rights and limited government', 'https://pacificlegal.org', 'CA', 'Sacramento', 25000000, true),
  ('Young Americas Foundation', '501(c)(3) Nonprofit', 'Conservative youth organization; operates Reagan Ranch', 'https://www.yaf.org', 'VA', 'Reston', 22000000, true),
  ('America First Policy Institute', 'Think Tank', 'Think tank aligned with the Trump movement', 'https://americafirstpolicy.com', 'DC', 'Washington', 25000000, true),
  ('Claremont Institute', 'Think Tank', 'Conservative think tank focused on restoring founding principles', 'https://www.claremont.org', 'CA', 'Claremont', 12000000, true),
  ('Save America PAC', 'Leadership PAC', 'Trump-aligned leadership PAC', NULL, 'FL', 'West Palm Beach', 100000000, true)
ON CONFLICT DO NOTHING;

-- Seed relationships
INSERT INTO relationships (entity_a_name, entity_a_type, entity_b_name, entity_b_type, relationship_type, description, active) VALUES
  ('Koch Industries', 'organization', 'Americans for Prosperity', 'organization', 'Founding', 'Koch brothers founded AFP as their primary political advocacy arm', true),
  ('Koch Industries', 'organization', 'Cato Institute', 'organization', 'Founding', 'Charles Koch co-founded Cato Institute', true),
  ('Koch Industries', 'organization', 'Club for Growth', 'organization', 'Donation / Financial', 'Koch network donors contribute to Club for Growth', true),
  ('Koch Industries', 'organization', 'Competitive Enterprise Institute', 'organization', 'Donation / Financial', 'Koch network provides major funding', true),
  ('American Conservative Union', 'organization', 'Heritage Foundation', 'organization', 'Coalition Partner', 'Heritage is a key participant in CPAC events', true),
  ('American Conservative Union', 'organization', 'Turning Point USA', 'organization', 'Coalition Partner', 'TPUSA participates in CPAC events', true),
  ('Federalist Society', 'organization', 'Heritage Foundation', 'organization', 'Coalition Partner', 'Collaborate on judicial nominations and conservative legal strategy', true),
  ('Federalist Society', 'organization', 'Alliance Defending Freedom', 'organization', 'Coalition Partner', 'Share legal strategy on religious liberty cases', true),
  ('Federalist Society', 'organization', 'Pacific Legal Foundation', 'organization', 'Coalition Partner', 'Coordinate on constitutional litigation', true),
  ('Senate Leadership Fund', 'organization', 'Republican National Committee', 'organization', 'Coalition Partner', 'Coordinates spending with RNC on Senate races', true),
  ('Congressional Leadership Fund', 'organization', 'Republican National Committee', 'organization', 'Coalition Partner', 'Coordinates spending with RNC on House races', true),
  ('Leadership Institute', 'organization', 'Turning Point USA', 'organization', 'Coalition Partner', 'Both focus on training young conservative activists', true),
  ('Leadership Institute', 'organization', 'Young Americas Foundation', 'organization', 'Coalition Partner', 'Coordinate on campus conservative programs', true),
  ('Heritage Foundation', 'organization', 'America First Policy Institute', 'organization', 'Coalition Partner', 'Both develop policy proposals for Republican administrations', true),
  ('Heritage Foundation', 'organization', 'Claremont Institute', 'organization', 'Coalition Partner', 'Share intellectual resources on constitutional originalism', true),
  ('Family Research Council', 'organization', 'Faith & Freedom Coalition', 'organization', 'Coalition Partner', 'Coordinate on Christian conservative political strategy', true),
  ('Family Research Council', 'organization', 'Susan B. Anthony Pro-Life America', 'organization', 'Coalition Partner', 'Coordinate on pro-life advocacy and legislation', true),
  ('Fox News', 'organization', 'The Daily Wire', 'organization', 'Coalition Partner', 'Dominant conservative media outlets with overlapping audiences', true),
  ('Fox News', 'organization', 'PragerU', 'organization', 'Coalition Partner', 'Cross-promote conservative media content', true),
  ('Save America PAC', 'organization', 'Republican National Committee', 'organization', 'Coalition Partner', 'Trump-aligned PAC coordinating with RNC', true),
  ('Hillsdale College', 'organization', 'Claremont Institute', 'organization', 'Advisory', 'Share faculty and intellectual leadership on founding principles', true)
ON CONFLICT DO NOTHING;
