-- Seed data: comprehensive list of people in the Republican/conservative ecosystem
-- 200+ entries covering donors, media figures, strategists, elected officials,
-- legal figures, think tank leaders, religious leaders, activists, lobbyists,
-- party officials, academics, MAGA figures, and Trump orbit

INSERT INTO people (name, role, title, description, state, party) VALUES

-- ══════════════════════════════════════════════════════════════════
-- 1. MAJOR REPUBLICAN DONORS
-- ══════════════════════════════════════════════════════════════════
('Charles Koch', 'Donor', 'CEO of Koch Industries', 'Billionaire industrialist who built a vast political network funding free-market conservative causes.', 'KS', 'Republican'),
('David Koch', 'Donor', 'Former EVP of Koch Industries', 'Late billionaire who co-founded Americans for Prosperity and funded libertarian-conservative organizations nationwide.', 'NY', 'Republican'),
('Rebekah Mercer', 'Donor', 'Co-owner of Mercer Family Foundation', 'Conservative megadonor who helped fund Breitbart News, Cambridge Analytica, and backed Trump in 2016.', 'NY', 'Republican'),
('Robert Mercer', 'Donor', 'Former Co-CEO of Renaissance Technologies', 'Billionaire hedge fund manager and major Republican donor who bankrolled conservative media and data operations.', 'NY', 'Republican'),
('Miriam Adelson', 'Donor', 'Owner of Las Vegas Sands Corp', 'Billionaire casino magnate and widow of Sheldon Adelson who is the single largest Republican donor in the country.', 'NV', 'Republican'),
('Peter Thiel', 'Donor', 'Co-founder of PayPal and Palantir', 'Tech billionaire and venture capitalist who backed J.D. Vance and other New Right candidates.', 'CA', 'Republican'),
('Richard Uihlein', 'Donor', 'CEO of Uline', 'Shipping supplies billionaire and one of the largest donors to conservative and Republican causes.', 'IL', 'Republican'),
('Elizabeth Uihlein', 'Donor', 'President of Uline', 'Conservative megadonor who along with husband Richard funds numerous Republican candidates and organizations.', 'IL', 'Republican'),
('Betsy DeVos', 'Donor', 'Former U.S. Secretary of Education', 'Billionaire Republican donor and former Trump cabinet member from the powerful DeVos family.', 'MI', 'Republican'),
('Dick DeVos', 'Donor', 'Former CEO of Amway', 'Billionaire businessman and major Republican donor from the Amway fortune.', 'MI', 'Republican'),
('Ken Griffin', 'Donor', 'CEO of Citadel', 'Hedge fund billionaire and major Republican donor who has given hundreds of millions to GOP candidates and causes.', 'FL', 'Republican'),
('Joe Ricketts', 'Donor', 'Founder of TD Ameritrade', 'Billionaire founder of TD Ameritrade and major funder of conservative organizations and Republican campaigns.', 'NE', 'Republican'),
('Todd Ricketts', 'Donor', 'Co-owner of Chicago Cubs', 'Republican donor and co-owner of the Chicago Cubs who served as RNC Finance Chairman.', 'NE', 'Republican'),
('Harlan Crow', 'Donor', 'Chairman of Crow Holdings', 'Dallas real estate billionaire and major conservative donor known for close ties to Supreme Court Justice Clarence Thomas.', 'TX', 'Republican'),
('Timothy Mellon', 'Donor', 'Chairman of Pan Am Systems', 'Billionaire heir to the Mellon banking fortune and one of the largest individual donors to Trump-aligned Super PACs.', 'WY', 'Republican'),
('Stephen Schwarzman', 'Donor', 'CEO of Blackstone Group', 'Billionaire private equity executive and major Republican fundraiser with close ties to multiple GOP administrations.', 'NY', 'Republican'),
('Paul Singer', 'Donor', 'Founder of Elliott Management', 'Hedge fund billionaire and major Republican donor who funds foreign policy hawks and pro-Israel causes.', 'NY', 'Republican'),
('Bernie Marcus', 'Donor', 'Co-founder of Home Depot', 'Billionaire retail magnate and prolific Republican donor who funds conservative think tanks and candidates.', 'GA', 'Republican'),
('Robert Kraft', 'Donor', 'Owner of New England Patriots', 'Billionaire sports owner and donor to both parties with significant Republican giving.', 'MA', 'Republican'),
('Harold Hamm', 'Donor', 'CEO of Continental Resources', 'Oil billionaire and major Republican donor who advises GOP candidates on energy policy.', 'OK', 'Republican'),
('Diane Hendricks', 'Donor', 'Chair of ABC Supply', 'Billionaire building materials executive and one of the largest female Republican donors in the country.', 'WI', 'Republican'),
('Jeff Yass', 'Donor', 'Co-founder of Susquehanna International Group', 'Trading firm billionaire and libertarian-leaning megadonor who is one of the largest political donors in the U.S.', 'PA', 'Republican'),
('Marc Andreessen', 'Donor', 'Co-founder of Andreessen Horowitz', 'Venture capital billionaire who aligned with Republicans and endorsed Trump in the 2024 cycle.', 'CA', 'Republican'),
('Elon Musk', 'Donor', 'CEO of Tesla and SpaceX', 'World richest person who became a major Trump ally, funded pro-Trump efforts, and led the Department of Government Efficiency.', 'TX', 'Republican'),
('Vivek Ramaswamy', 'Donor', 'Entrepreneur and Former Presidential Candidate', 'Biotech entrepreneur who ran for the 2024 GOP presidential nomination and co-led DOGE with Elon Musk.', 'OH', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 2. CONSERVATIVE MEDIA FIGURES
-- ══════════════════════════════════════════════════════════════════
('Tucker Carlson', 'Media Figure', 'Host of Tucker Carlson Network', 'Former Fox News primetime host and one of the most influential voices in conservative media.', 'ME', 'Republican'),
('Sean Hannity', 'Media Figure', 'Host of Hannity on Fox News', 'Longtime Fox News host and close Trump ally who is one of the most-watched cable news personalities.', 'NY', 'Republican'),
('Laura Ingraham', 'Media Figure', 'Host of The Ingraham Angle on Fox News', 'Fox News primetime host and conservative commentator known for populist-right positions.', 'VA', 'Republican'),
('Mark Levin', 'Media Figure', 'Host of Life, Liberty & Levin', 'Conservative radio host, Fox News host, and constitutional lawyer with a large national audience.', 'VA', 'Republican'),
('Ben Shapiro', 'Media Figure', 'Co-founder and Host at The Daily Wire', 'Conservative commentator, author, and co-founder of The Daily Wire media company.', 'TN', 'Republican'),
('Dan Bongino', 'Media Figure', 'Conservative Podcast Host', 'Former Secret Service agent turned conservative media personality with one of the top-rated podcasts.', 'FL', 'Republican'),
('Jesse Watters', 'Media Figure', 'Host of Jesse Watters Primetime on Fox News', 'Fox News primetime host who replaced Tucker Carlson in the 8 PM slot.', 'NY', 'Republican'),
('Maria Bartiromo', 'Media Figure', 'Host of Mornings with Maria on Fox Business', 'Fox Business anchor known for conservative economic commentary and political interviews.', 'NY', 'Republican'),
('Jeanine Pirro', 'Media Figure', 'Co-host of The Five on Fox News', 'Former judge and prosecutor who became a prominent Fox News personality and Trump ally.', 'NY', 'Republican'),
('Greg Gutfeld', 'Media Figure', 'Host of Gutfeld! on Fox News', 'Fox News late-night host whose show frequently beats traditional late-night competitors in ratings.', 'NY', 'Republican'),
('Charlie Kirk', 'Media Figure', 'Founder of Turning Point USA', 'Conservative activist and media personality who built TPUSA into a major youth political organization.', 'AZ', 'Republican'),
('Candace Owens', 'Media Figure', 'Conservative Commentator', 'Conservative commentator and media personality known for outreach to Black Americans on behalf of the GOP.', 'TN', 'Republican'),
('Dennis Prager', 'Media Figure', 'Founder of PragerU', 'Conservative radio host and founder of PragerU, a major conservative digital media nonprofit.', 'CA', 'Republican'),
('Glenn Beck', 'Media Figure', 'Founder of TheBlaze', 'Conservative media entrepreneur, radio host, and founder of Blaze Media.', 'TX', 'Republican'),
('Steve Bannon', 'Media Figure', 'Host of War Room Podcast', 'Former Trump White House Chief Strategist and Breitbart chairman who hosts the influential War Room podcast.', 'DC', 'Republican'),
('Megyn Kelly', 'Media Figure', 'Host of The Megyn Kelly Show', 'Former Fox News and NBC anchor who hosts a top-rated independent podcast.', 'NY', 'Republican'),
('Hugh Hewitt', 'Media Figure', 'Conservative Radio Host', 'Conservative radio host, author, and law professor with a national syndicated show.', 'CA', 'Republican'),
('Bret Baier', 'Media Figure', 'Chief Political Anchor at Fox News', 'Fox News chief political anchor and host of Special Report.', 'DC', 'Republican'),
('Rachel Campos-Duffy', 'Media Figure', 'Co-host of Fox & Friends Weekend', 'Fox News host and conservative commentator married to former Rep. Sean Duffy.', 'WI', 'Republican'),
('Matt Walsh', 'Media Figure', 'Host at The Daily Wire', 'Conservative commentator and filmmaker at The Daily Wire known for cultural commentary.', 'TN', 'Republican'),
('Michael Knowles', 'Media Figure', 'Host at The Daily Wire', 'Conservative commentator and podcast host at The Daily Wire.', 'TN', 'Republican'),
('Joe Rogan', 'Media Figure', 'Host of The Joe Rogan Experience', 'Most popular podcaster in the world whose platform amplifies conservative and libertarian voices and who endorsed Trump in 2024.', 'TX', 'Independent'),
('Dinesh D''Souza', 'Media Figure', 'Conservative Filmmaker and Author', 'Conservative author and filmmaker known for political documentaries and cultural commentary.', 'TX', 'Republican'),
('Sebastian Gorka', 'Media Figure', 'Host of America First on Salem Radio', 'Former Trump advisor turned conservative radio host and media personality.', 'VA', 'Republican'),
('Jack Posobiec', 'Media Figure', 'Senior Editor at Human Events', 'Conservative media personality and political commentator aligned with the MAGA movement.', 'DC', 'Republican'),
('Benny Johnson', 'Media Figure', 'Chief Creative Officer at Turning Point USA', 'Conservative social media personality and content creator with a large online following.', 'DC', 'Republican'),
('Tim Pool', 'Media Figure', 'Host of Timcast', 'Independent media personality and podcaster popular in right-leaning online spaces.', 'MD', 'Republican'),
('Steve Deace', 'Media Figure', 'Host on BlazeTV', 'Conservative radio host and commentator on BlazeTV focused on Christian conservatism.', 'IA', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 3. REPUBLICAN STRATEGISTS AND CONSULTANTS
-- ══════════════════════════════════════════════════════════════════
('Karl Rove', 'Strategist', 'Republican Strategist and Fox News Contributor', 'Legendary GOP strategist known as Bush''s Brain who architected George W. Bush''s presidential victories.', 'TX', 'Republican'),
('Kellyanne Conway', 'Strategist', 'Former Counselor to President Trump', 'First woman to successfully manage a presidential campaign (Trump 2016) and senior White House advisor.', 'NJ', 'Republican'),
('Chris LaCivita', 'Strategist', 'Senior Advisor to Trump 2024 Campaign', 'Veteran Republican operative who co-managed the Trump 2024 presidential campaign.', 'VA', 'Republican'),
('Susie Wiles', 'Strategist', 'White House Chief of Staff', 'Veteran Florida Republican operative who managed Trump''s 2024 campaign and became the first female White House Chief of Staff.', 'FL', 'Republican'),
('Brad Parscale', 'Strategist', 'Former Trump 2020 Campaign Manager', 'Digital strategist who managed Trump''s 2020 campaign and ran digital operations for the 2016 campaign.', 'TX', 'Republican'),
('Corey Lewandowski', 'Strategist', 'Republican Political Operative', 'Trump''s first 2016 campaign manager who remains in the Trump political orbit.', 'NH', 'Republican'),
('David Bossie', 'Strategist', 'President of Citizens United', 'Conservative activist and strategist who served as Trump''s deputy campaign manager in 2016.', 'MD', 'Republican'),
('Jason Miller', 'Strategist', 'CEO of Gettr', 'Former Trump senior advisor and communications strategist who founded the social media platform Gettr.', 'DC', 'Republican'),
('Boris Epshteyn', 'Strategist', 'Senior Advisor to Donald Trump', 'Political strategist and attorney who serves as a key advisor in Trump''s political operation.', 'NY', 'Republican'),
('Roger Stone', 'Strategist', 'Republican Political Consultant', 'Longtime Republican operative and self-described dirty trickster who has worked in GOP politics since Nixon.', 'FL', 'Republican'),
('Frank Luntz', 'Strategist', 'Republican Pollster and Communications Consultant', 'Prominent Republican pollster and messaging expert known for focus group testing of political language.', 'DC', 'Republican'),
('Tony Fabrizio', 'Pollster', 'Republican Pollster', 'Top Republican pollster who served as chief pollster for Trump''s presidential campaigns.', 'VA', 'Republican'),
('Jeff Roe', 'Strategist', 'Republican Campaign Consultant', 'Republican campaign strategist who managed Ted Cruz''s 2016 presidential campaign and DeSantis 2024.', 'MO', 'Republican'),
('Mike Murphy', 'Strategist', 'Republican Media Consultant', 'Veteran GOP media strategist known for work with Jeb Bush, John McCain, and Mitt Romney.', 'CA', 'Republican'),
('Sara Craig', 'Strategist', 'GOP Digital Strategist', 'Republican digital strategist who has run major digital campaign operations.', 'DC', 'Republican'),
('Katie Walsh', 'Strategist', 'Republican Political Operative', 'Former RNC Chief of Staff and former deputy chief of staff in the Trump White House.', 'DC', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 4. KEY REPUBLICAN ELECTED OFFICIALS
-- ══════════════════════════════════════════════════════════════════
-- U.S. Senators
('Mitch McConnell', 'Elected Official', 'U.S. Senator from Kentucky', 'Longest-serving Senate Republican leader in history who shaped the federal judiciary through strategic confirmations.', 'KY', 'Republican'),
('John Thune', 'Elected Official', 'U.S. Senate Majority Leader', 'Senior senator from South Dakota who became Senate Majority Leader in 2025.', 'SD', 'Republican'),
('Ted Cruz', 'Elected Official', 'U.S. Senator from Texas', 'Conservative senator, former presidential candidate, and prominent voice on judicial and immigration issues.', 'TX', 'Republican'),
('Marco Rubio', 'Elected Official', 'U.S. Secretary of State', 'Former Florida senator who became Trump''s Secretary of State in 2025.', 'FL', 'Republican'),
('Lindsey Graham', 'Elected Official', 'U.S. Senator from South Carolina', 'Senior senator and close Trump ally who chairs the Senate Judiciary Committee.', 'SC', 'Republican'),
('Tom Cotton', 'Elected Official', 'U.S. Senator from Arkansas', 'Hawkish conservative senator and Army veteran considered a future presidential contender.', 'AR', 'Republican'),
('Josh Hawley', 'Elected Official', 'U.S. Senator from Missouri', 'Populist conservative senator known for challenging Big Tech and his fist-pump on January 6.', 'MO', 'Republican'),
('J.D. Vance', 'Elected Official', 'Vice President of the United States', 'Author of Hillbilly Elegy who became senator and then Trump''s vice presidential pick in 2024.', 'OH', 'Republican'),
('Rick Scott', 'Elected Official', 'U.S. Senator from Florida', 'Former Florida governor and senator who chaired the NRSC.', 'FL', 'Republican'),
('Tim Scott', 'Elected Official', 'U.S. Senator from South Carolina', 'First Black Republican senator from the South since Reconstruction who ran for president in 2024.', 'SC', 'Republican'),
('Rand Paul', 'Elected Official', 'U.S. Senator from Kentucky', 'Libertarian-leaning senator and ophthalmologist who champions limited government and civil liberties.', 'KY', 'Republican'),
('Mike Lee', 'Elected Official', 'U.S. Senator from Utah', 'Constitutional conservative senator and former Supreme Court clerk known for strict originalism.', 'UT', 'Republican'),
('John Cornyn', 'Elected Official', 'U.S. Senator from Texas', 'Senior Texas senator and former Senate Republican Whip.', 'TX', 'Republican'),
('Chuck Grassley', 'Elected Official', 'U.S. Senator from Iowa', 'Longest-serving Republican senator and former Judiciary Committee chairman.', 'IA', 'Republican'),
('Susan Collins', 'Elected Official', 'U.S. Senator from Maine', 'Moderate Republican senator who is often a key swing vote on major legislation.', 'ME', 'Republican'),
('Lisa Murkowski', 'Elected Official', 'U.S. Senator from Alaska', 'Moderate Republican senator known for independent voting record.', 'AK', 'Republican'),
('Bill Hagerty', 'Elected Official', 'U.S. Senator from Tennessee', 'Former U.S. Ambassador to Japan and Trump-aligned senator.', 'TN', 'Republican'),
('Roger Marshall', 'Elected Official', 'U.S. Senator from Kansas', 'Physician and senator aligned with conservative health care and agricultural policy.', 'KS', 'Republican'),
('John Barrasso', 'Elected Official', 'U.S. Senate Republican Whip', 'Wyoming senator serving as Senate Republican Whip.', 'WY', 'Republican'),
('Marsha Blackburn', 'Elected Official', 'U.S. Senator from Tennessee', 'Conservative senator known for work on tech regulation and cultural issues.', 'TN', 'Republican'),
('Ron Johnson', 'Elected Official', 'U.S. Senator from Wisconsin', 'Conservative businessman-turned-senator known for investigations and skepticism of government narratives.', 'WI', 'Republican'),
('Tommy Tuberville', 'Elected Official', 'U.S. Senator from Alabama', 'Former college football coach turned senator who blocked military promotions over Pentagon abortion policy.', 'AL', 'Republican'),
('Katie Britt', 'Elected Official', 'U.S. Senator from Alabama', 'Youngest Republican woman ever elected to the Senate.', 'AL', 'Republican'),
('Eric Schmitt', 'Elected Official', 'U.S. Senator from Missouri', 'Former Missouri Attorney General elected to the Senate in 2022.', 'MO', 'Republican'),

-- U.S. House Leadership & Key Members
('Mike Johnson', 'Elected Official', 'Speaker of the U.S. House of Representatives', 'Louisiana congressman who became Speaker of the House in October 2023.', 'LA', 'Republican'),
('Steve Scalise', 'Elected Official', 'U.S. House Majority Leader', 'House Majority Leader and survivor of the 2017 congressional baseball shooting.', 'LA', 'Republican'),
('Tom Emmer', 'Elected Official', 'U.S. House Majority Whip', 'House Majority Whip from Minnesota.', 'MN', 'Republican'),
('Elise Stefanik', 'Elected Official', 'U.S. Ambassador to the United Nations', 'Former House Republican Conference Chair who became Trump''s UN Ambassador.', 'NY', 'Republican'),
('Jim Jordan', 'Elected Official', 'Chairman of the House Judiciary Committee', 'Conservative firebrand and founding member of the House Freedom Caucus.', 'OH', 'Republican'),
('Matt Gaetz', 'Elected Official', 'Former U.S. Representative from Florida', 'Controversial pro-Trump congressman who was nominated for Attorney General before withdrawing.', 'FL', 'Republican'),
('Marjorie Taylor Greene', 'Elected Official', 'U.S. Representative from Georgia', 'Firebrand MAGA congresswoman who became a prominent Trump ally and committee member.', 'GA', 'Republican'),
('Lauren Boebert', 'Elected Official', 'U.S. Representative from Colorado', 'Outspoken conservative congresswoman who switched districts for the 2024 election.', 'CO', 'Republican'),
('Byron Donalds', 'Elected Official', 'U.S. Representative from Florida', 'Rising conservative star in the House and potential future statewide candidate.', 'FL', 'Republican'),
('Andy Biggs', 'Elected Official', 'U.S. Representative from Arizona', 'Former House Freedom Caucus chairman and conservative hardliner.', 'AZ', 'Republican'),
('Chip Roy', 'Elected Official', 'U.S. Representative from Texas', 'Conservative congressman and former Ted Cruz chief of staff known for procedural fights.', 'TX', 'Republican'),
('Dan Crenshaw', 'Elected Official', 'U.S. Representative from Texas', 'Former Navy SEAL and congressman known for moderate-conservative positions.', 'TX', 'Republican'),
('Nancy Mace', 'Elected Official', 'U.S. Representative from South Carolina', 'Republican congresswoman and first female graduate of The Citadel.', 'SC', 'Republican'),
('Anna Paulina Luna', 'Elected Official', 'U.S. Representative from Florida', 'Military veteran and conservative congresswoman from the Tampa Bay area.', 'FL', 'Republican'),
('Wesley Hunt', 'Elected Official', 'U.S. Representative from Texas', 'Army veteran and rising Republican star in the Texas delegation.', 'TX', 'Republican'),
('Mike Waltz', 'Elected Official', 'National Security Advisor', 'Former congressman and Green Beret who became Trump''s National Security Advisor.', 'FL', 'Republican'),
('James Comer', 'Elected Official', 'Chairman of House Oversight Committee', 'Kentucky congressman who led investigations into the Biden family.', 'KY', 'Republican'),
('Patrick McHenry', 'Elected Official', 'Former U.S. Representative from North Carolina', 'Former House Financial Services Chairman who served as interim Speaker in 2023.', 'NC', 'Republican'),
('Kevin McCarthy', 'Elected Official', 'Former Speaker of the House', 'Former House Speaker who was ousted in an unprecedented vote in October 2023.', 'CA', 'Republican'),
('Bob Good', 'Elected Official', 'Former U.S. Representative from Virginia', 'Former House Freedom Caucus chairman who lost his 2024 primary.', 'VA', 'Republican'),

-- Governors
('Ron DeSantis', 'Elected Official', 'Governor of Florida', 'Conservative governor who ran for the 2024 GOP presidential nomination and is known for culture war battles.', 'FL', 'Republican'),
('Greg Abbott', 'Elected Official', 'Governor of Texas', 'Texas governor known for aggressive border security measures including Operation Lone Star.', 'TX', 'Republican'),
('Glenn Youngkin', 'Elected Official', 'Governor of Virginia', 'Former Carlyle Group executive who won the Virginia governorship in 2021 on education issues.', 'VA', 'Republican'),
('Brian Kemp', 'Elected Official', 'Governor of Georgia', 'Georgia governor who resisted Trump''s pressure to overturn 2020 election results and won reelection decisively.', 'GA', 'Republican'),
('Kim Reynolds', 'Elected Official', 'Governor of Iowa', 'Iowa governor who endorsed Ron DeSantis in the 2024 Republican primary.', 'IA', 'Republican'),
('Sarah Huckabee Sanders', 'Elected Official', 'Governor of Arkansas', 'Former Trump White House Press Secretary who was elected governor of Arkansas in 2022.', 'AR', 'Republican'),
('Kristi Noem', 'Elected Official', 'Secretary of Homeland Security', 'Former South Dakota governor who became Trump''s Secretary of Homeland Security.', 'SD', 'Republican'),
('Doug Burgum', 'Elected Official', 'Secretary of the Interior', 'Former North Dakota governor and tech entrepreneur who became Trump''s Interior Secretary.', 'ND', 'Republican'),
('Bill Lee', 'Elected Official', 'Governor of Tennessee', 'Conservative businessman-turned-governor of Tennessee.', 'TN', 'Republican'),
('Tate Reeves', 'Elected Official', 'Governor of Mississippi', 'Conservative governor of Mississippi.', 'MS', 'Republican'),
('Jeff Landry', 'Elected Official', 'Governor of Louisiana', 'Former attorney general elected governor of Louisiana in 2023 on a conservative platform.', 'LA', 'Republican'),
('Mike DeWine', 'Elected Official', 'Governor of Ohio', 'Moderate Republican governor of Ohio.', 'OH', 'Republican'),

-- Former Elected Officials / Prominent Republicans
('Donald Trump', 'Elected Official', '47th President of the United States', 'The 45th and 47th President who reshaped the Republican Party around populist nationalism and the MAGA movement.', 'FL', 'Republican'),
('Mike Pence', 'Elected Official', 'Former Vice President of the United States', 'Former VP and Indiana governor who broke with Trump over January 6 and ran unsuccessfully for president in 2024.', 'IN', 'Republican'),
('Nikki Haley', 'Elected Official', 'Former U.S. Ambassador to the United Nations', 'Former South Carolina governor and UN Ambassador who was Trump''s last major primary challenger in 2024.', 'SC', 'Republican'),
('Mike Pompeo', 'Elected Official', 'Former U.S. Secretary of State', 'Former CIA Director and Secretary of State under Trump who ran briefly for president in 2024.', 'KS', 'Republican'),
('Chris Christie', 'Elected Official', 'Former Governor of New Jersey', 'Former NJ governor and U.S. Attorney who ran as an anti-Trump candidate in the 2024 primary.', 'NJ', 'Republican'),
('Asa Hutchinson', 'Elected Official', 'Former Governor of Arkansas', 'Former Arkansas governor who ran for president in 2024 as a traditional conservative.', 'AR', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 5. CONSERVATIVE LEGAL FIGURES
-- ══════════════════════════════════════════════════════════════════
('Leonard Leo', 'Strategist', 'Co-chairman of the Federalist Society', 'Architect of the conservative supermajority on the Supreme Court who channels hundreds of millions to right-leaning legal causes.', 'DC', 'Republican'),
('Eugene Meyer', 'Executive', 'President of the Federalist Society', 'President of the Federalist Society who oversees its nationwide network of conservative and libertarian lawyers.', 'DC', 'Republican'),
('Cleta Mitchell', 'Lawyer', 'Conservative Election Lawyer', 'Conservative attorney who participated in Trump''s call to Georgia officials and now leads election integrity efforts.', 'DC', 'Republican'),
('Mark Paoletta', 'Lawyer', 'Conservative Attorney', 'Conservative lawyer who served as OMB General Counsel and is close to Justice Clarence Thomas.', 'DC', 'Republican'),
('John Eastman', 'Lawyer', 'Former Law Professor', 'Conservative attorney and former Claremont Institute fellow who devised the theory to overturn the 2020 election.', 'CA', 'Republican'),
('Todd Gaziano', 'Lawyer', 'President of the Pacific Legal Foundation', 'Conservative legal scholar who leads the Pacific Legal Foundation in constitutional litigation.', 'CA', 'Republican'),
('Kristen Waggoner', 'Lawyer', 'CEO of Alliance Defending Freedom', 'Leader of Alliance Defending Freedom, arguing major religious liberty cases before the Supreme Court.', 'AZ', 'Republican'),
('Michael Bowe', 'Lawyer', 'Partner at Brown Rudnick', 'Conservative litigator who has represented Trump and other high-profile Republican clients.', 'NY', 'Republican'),
('Jay Sekulow', 'Lawyer', 'Chief Counsel of American Center for Law and Justice', 'Conservative attorney who served on Trump''s impeachment defense team and leads the ACLJ.', 'VA', 'Republican'),
('Alina Habba', 'Lawyer', 'Counselor to President Trump', 'Attorney who represented Trump in multiple civil cases and became a prominent MAGA media figure.', 'NJ', 'Republican'),
('Mike Davis', 'Lawyer', 'Founder of Article III Project', 'Conservative legal activist who founded the Article III Project to support Trump''s judicial nominees.', 'DC', 'Republican'),
('Jesse Binnall', 'Lawyer', 'Republican Election Attorney', 'Conservative election lawyer who has represented Trump and Republican causes in major litigation.', 'VA', 'Republican'),
('William Consovoy', 'Lawyer', 'Founding Partner of Consovoy McCarthy', 'Conservative Supreme Court litigator whose firm has handled key Republican voting rights cases.', 'VA', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 6. THINK TANK LEADERS
-- ══════════════════════════════════════════════════════════════════
('Kevin Roberts', 'Executive', 'President of the Heritage Foundation', 'Leader of the Heritage Foundation who oversaw the creation of Project 2025.', 'DC', 'Republican'),
('Robert Doar', 'Executive', 'President of the American Enterprise Institute', 'President of AEI who leads the center-right think tank focused on public policy research.', 'DC', 'Republican'),
('Peter Berkowitz', 'Executive', 'Director of the Hoover Institution', 'Director of the Hoover Institution at Stanford University focusing on conservative policy research.', 'CA', 'Republican'),
('Ed Feulner', 'Executive', 'Co-founder of the Heritage Foundation', 'Co-founder and former longtime president of the Heritage Foundation who built it into the leading conservative think tank.', 'DC', 'Republican'),
('Amy Kremer', 'Other', 'Co-founder of Women for America First', 'Conservative activist and Tea Party organizer who helped organize the January 6 rally.', 'GA', 'Republican'),
('Brooke Rollins', 'Executive', 'President of America First Policy Institute', 'Former Trump Domestic Policy Council director who leads the MAGA-aligned think tank.', 'TX', 'Republican'),
('Ryan Anderson', 'Executive', 'President of the Ethics and Public Policy Center', 'Conservative intellectual and president of EPPC focused on applying Judeo-Christian principles to public policy.', 'DC', 'Republican'),
('Christopher DeMuth', 'Executive', 'Distinguished Fellow at Hudson Institute', 'Former longtime AEI president and influential conservative intellectual.', 'DC', 'Republican'),
('John Yoo', 'Other', 'Professor at UC Berkeley Law', 'Conservative legal scholar at the Hoover Institution known for expansive executive power theories.', 'CA', 'Republican'),
('Kay Cole James', 'Executive', 'Former President of the Heritage Foundation', 'Former Heritage Foundation president and conservative leader in education and policy.', 'VA', 'Republican'),
('Peter Wallison', 'Executive', 'Senior Fellow at AEI', 'Conservative scholar and former Reagan White House Counsel known for financial regulation expertise.', 'DC', 'Republican'),
('Arthur Brooks', 'Executive', 'Former President of AEI', 'Former AEI president, author, and professor at Harvard who promoted conservative ideas on poverty and happiness.', 'DC', 'Republican'),
('Ryan Streeter', 'Executive', 'Director of Domestic Policy Studies at AEI', 'Policy scholar at AEI focusing on conservative approaches to opportunity and upward mobility.', 'DC', 'Republican'),
('Roger Kimball', 'Executive', 'Editor of The New Criterion', 'Conservative intellectual, publisher of Encounter Books, and editor of The New Criterion.', 'CT', 'Republican'),
('John Allison', 'Executive', 'Former President of the Cato Institute', 'Former CEO of BB&T and Cato Institute president who promotes free-market principles.', 'DC', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 7. RELIGIOUS RIGHT LEADERS
-- ══════════════════════════════════════════════════════════════════
('Ralph Reed', 'Strategist', 'Chairman of Faith & Freedom Coalition', 'Veteran Christian conservative strategist who leads the influential Faith and Freedom Coalition.', 'GA', 'Republican'),
('Tony Perkins', 'Executive', 'President of Family Research Council', 'Leader of the Family Research Council and influential voice in evangelical conservative politics.', 'DC', 'Republican'),
('Robert Jeffress', 'Other', 'Pastor of First Baptist Church Dallas', 'Megachurch pastor and prominent evangelical supporter of Donald Trump.', 'TX', 'Republican'),
('Franklin Graham', 'Other', 'President of Samaritan''s Purse', 'Evangelical leader and son of Billy Graham who is a prominent political voice for Christian conservatism.', 'NC', 'Republican'),
('Paula White', 'Other', 'Evangelical Pastor and Trump Spiritual Advisor', 'Prosperity gospel pastor who served as Trump''s personal spiritual advisor and led the White House Faith Office.', 'FL', 'Republican'),
('James Dobson', 'Other', 'Founder of Focus on the Family', 'Evangelical psychologist and radio host who founded Focus on the Family and shaped the religious right for decades.', 'CO', 'Republican'),
('Jerry Falwell Jr.', 'Other', 'Former President of Liberty University', 'Former leader of Liberty University who was a key early endorser of Trump in 2016 before his resignation.', 'VA', 'Republican'),
('Jack Graham', 'Other', 'Pastor of Prestonwood Baptist Church', 'Megachurch pastor and former Southern Baptist Convention president who is active in Republican politics.', 'TX', 'Republican'),
('Jentezen Franklin', 'Other', 'Pastor of Free Chapel', 'Megachurch pastor and evangelical leader with close ties to Republican politicians.', 'GA', 'Republican'),
('Gary Bauer', 'Other', 'President of American Values', 'Conservative Christian leader, former presidential candidate, and longtime family values advocate.', 'DC', 'Republican'),
('Al Mohler', 'Other', 'President of Southern Baptist Theological Seminary', 'Influential evangelical intellectual and president of the largest Southern Baptist seminary.', 'KY', 'Republican'),
('Jack Hibbs', 'Other', 'Pastor of Calvary Chapel Chino Hills', 'California megachurch pastor and outspoken conservative Christian political activist.', 'CA', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 8. CONSERVATIVE ACTIVISTS AND MOVEMENT LEADERS
-- ══════════════════════════════════════════════════════════════════
('Grover Norquist', 'Other', 'President of Americans for Tax Reform', 'Anti-tax crusader who created the Taxpayer Protection Pledge signed by most Republican officeholders.', 'DC', 'Republican'),
('Morton Blackwell', 'Other', 'Founder of the Leadership Institute', 'Conservative movement institution builder who trained thousands of conservative activists and campaign professionals.', 'VA', 'Republican'),
('Penny Nance', 'Other', 'CEO of Concerned Women for America', 'Leader of the largest public policy women''s organization in the nation advocating for conservative values.', 'DC', 'Republican'),
('Marjorie Dannenfelser', 'Other', 'President of Susan B. Anthony Pro-Life America', 'Leading anti-abortion activist who has shaped Republican presidential candidates'' positions on the issue.', 'VA', 'Republican'),
('Tom Fitton', 'Other', 'President of Judicial Watch', 'Conservative activist who leads Judicial Watch in filing FOIA lawsuits against the federal government.', 'DC', 'Republican'),
('Jenny Beth Martin', 'Other', 'Co-founder of Tea Party Patriots', 'Tea Party movement leader and co-founder of Tea Party Patriots.', 'GA', 'Republican'),
('Matt Schlapp', 'Other', 'Chairman of the American Conservative Union', 'Chairman of the ACU and organizer of the annual CPAC conference.', 'VA', 'Republican'),
('Scott Presler', 'Other', 'Republican Voter Registration Activist', 'Grassroots conservative activist known for massive voter registration drives in swing states.', 'VA', 'Republican'),
('Christopher Rufo', 'Other', 'Senior Fellow at Manhattan Institute', 'Conservative activist and intellectual who led campaigns against critical race theory and DEI in institutions.', 'WA', 'Republican'),
('Jim Bopp', 'Lawyer', 'Conservative Election Law Attorney', 'Influential Republican election lawyer who has argued major campaign finance cases before the Supreme Court.', 'IN', 'Republican'),
('Mark Meckler', 'Other', 'President of Convention of States Action', 'Conservative activist who co-founded the Tea Party Patriots and now leads the Article V convention movement.', 'TX', 'Republican'),
('James O''Keefe', 'Other', 'Founder of O''Keefe Media Group', 'Controversial conservative activist and undercover journalist who founded Project Veritas and later O''Keefe Media Group.', 'NY', 'Republican'),
('Lara Trump', 'Party Official', 'Former RNC Co-Chair', 'Donald Trump''s daughter-in-law who served as RNC Co-Chair during the 2024 campaign cycle.', 'FL', 'Republican'),
('Terry Schilling', 'Other', 'President of American Principles Project', 'Conservative activist leading APP''s focus on social conservative and anti-trans policies in elections.', 'DC', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 9. REPUBLICAN LOBBYISTS
-- ══════════════════════════════════════════════════════════════════
('Brian Ballard', 'Lobbyist', 'CEO of Ballard Partners', 'Top Republican lobbyist in Washington with close ties to Trump and Florida Republican politics.', 'FL', 'Republican'),
('Jeff Miller', 'Lobbyist', 'Co-founder of Miller Strategies', 'Prominent GOP lobbyist and fundraiser with close ties to the Trump orbit.', 'DC', 'Republican'),
('David Safavian', 'Lobbyist', 'General Counsel at American Conservative Union', 'Republican lobbyist and lawyer serving at the ACU.', 'VA', 'Republican'),
('Ed Rogers', 'Lobbyist', 'Chairman of BGR Group', 'Veteran Republican lobbyist and Bush 41 White House alumnus who runs a top K Street firm.', 'DC', 'Republican'),
('Charlie Black', 'Lobbyist', 'Chairman of Prime Policy Group', 'Longtime Republican lobbyist and political advisor who has counseled multiple presidential campaigns.', 'DC', 'Republican'),
('Wayne Berman', 'Lobbyist', 'Senior Advisor at Blackstone Group', 'Veteran Republican fundraiser and lobbyist who is one of the top GOP bundlers.', 'DC', 'Republican'),
('David Urban', 'Lobbyist', 'Founder of American Continental Group', 'Republican lobbyist and strategist who managed Trump''s 2016 Pennsylvania campaign.', 'PA', 'Republican'),
('Nick Ayers', 'Lobbyist', 'Republican Operative and Consultant', 'Former chief of staff to VP Pence and top Republican operative turned consultant.', 'GA', 'Republican'),
('Stewart Rhodes', 'Other', 'Founder of Oath Keepers', 'Founder of the Oath Keepers militia group convicted of seditious conspiracy related to January 6.', 'TX', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 10. GOP PARTY OFFICIALS
-- ══════════════════════════════════════════════════════════════════
('Michael Whatley', 'Party Official', 'Chairman of the Republican National Committee', 'RNC Chairman who took over party leadership for the 2024 election cycle.', 'NC', 'Republican'),
('Ronna McDaniel', 'Party Official', 'Former RNC Chairwoman', 'Former Republican National Committee chairwoman who led the party from 2017 to 2024.', 'MI', 'Republican'),
('Chris Carr', 'Party Official', 'RNC Chief Counsel', 'Republican attorney serving as chief legal counsel for the Republican National Committee.', 'DC', 'Republican'),
('Tommy Hicks', 'Party Official', 'Former RNC Co-Chair', 'Former RNC Co-Chair and close Trump ally in Republican Party operations.', 'TX', 'Republican'),
('Henry Barbour', 'Party Official', 'RNC Committeeman from Mississippi', 'Longtime RNC member and nephew of former Mississippi Governor Haley Barbour.', 'MS', 'Republican'),
('Jim Marchant', 'Party Official', 'Chairman of Nevada Republican Party', 'Conservative activist who leads the Nevada Republican Party.', 'NV', 'Republican'),
('Drew McKissick', 'Party Official', 'Former Chairman of South Carolina Republican Party', 'Former state party chairman who was closely aligned with Trump.', 'SC', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 11. CONSERVATIVE ACADEMICS AND INTELLECTUALS
-- ══════════════════════════════════════════════════════════════════
('Victor Davis Hanson', 'Other', 'Senior Fellow at Hoover Institution', 'Conservative classicist, military historian, and political commentator at the Hoover Institution.', 'CA', 'Republican'),
('Thomas Sowell', 'Other', 'Senior Fellow at Hoover Institution', 'Renowned conservative economist and social theorist whose work on race and economics is widely influential.', 'CA', 'Republican'),
('Larry Arnn', 'Other', 'President of Hillsdale College', 'President of Hillsdale College who has made it a bastion of conservative education and constitutional thought.', 'MI', 'Republican'),
('Michael Anton', 'Other', 'Fellow at Claremont Institute', 'Author of the influential "Flight 93 Election" essay and former Trump NSC official.', 'DC', 'Republican'),
('Adrian Vermeule', 'Other', 'Professor at Harvard Law School', 'Conservative legal scholar who advocates for common-good constitutionalism and post-liberal conservatism.', 'MA', 'Republican'),
('Patrick Deneen', 'Other', 'Professor at University of Notre Dame', 'Post-liberal conservative political theorist and author of "Why Liberalism Failed."', 'IN', 'Republican'),
('Sohrab Ahmari', 'Other', 'Editor and Author', 'Conservative intellectual and columnist who advocates for a more interventionist conservatism on cultural issues.', 'NY', 'Republican'),
('Charles Murray', 'Other', 'Fellow Emeritus at AEI', 'Controversial conservative social scientist and author of "Coming Apart" and "The Bell Curve."', 'MD', 'Republican'),
('Yuval Levin', 'Other', 'Director of Social, Cultural, and Constitutional Studies at AEI', 'Conservative policy intellectual and founding editor of National Affairs.', 'DC', 'Republican'),
('Rich Lowry', 'Other', 'Editor-in-Chief of National Review', 'Editor of National Review, the flagship conservative magazine founded by William F. Buckley Jr.', 'NY', 'Republican'),
('Ross Douthat', 'Other', 'Opinion Columnist at The New York Times', 'Conservative columnist at the New York Times and influential voice in right-of-center intellectual debates.', 'CT', 'Republican'),
('Matthew Continetti', 'Other', 'Senior Fellow at AEI', 'Conservative intellectual and author of "The Right," a history of the American conservative movement.', 'DC', 'Republican'),
('Michael Brendan Dougherty', 'Other', 'Senior Writer at National Review', 'Conservative writer and author focused on traditionalist conservatism and Catholic thought.', 'NY', 'Republican'),
('Mollie Hemingway', 'Media Figure', 'Editor-in-Chief of The Federalist', 'Conservative journalist and editor-in-chief of The Federalist who is a Fox News contributor.', 'DC', 'Republican'),
('Ben Domenech', 'Media Figure', 'Co-founder of The Federalist', 'Conservative media figure who co-founded The Federalist and hosts The Ben Domenech Podcast.', 'DC', 'Republican'),
('Oren Cass', 'Other', 'Executive Director of American Compass', 'Conservative policy intellectual who founded American Compass to challenge free-market orthodoxy from the right.', 'NY', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 12. MAGA MOVEMENT FIGURES
-- ══════════════════════════════════════════════════════════════════
('Michael Flynn', 'Other', 'Former National Security Advisor', 'Retired Army general and former Trump National Security Advisor who became a leading figure in MAGA activism.', 'FL', 'Republican'),
('Kash Patel', 'Executive', 'Director of the FBI', 'Former Trump NSC and Pentagon official who became Trump''s FBI Director in 2025.', 'DC', 'Republican'),
('Stephen Miller', 'Strategist', 'Deputy Chief of Staff for Policy', 'Architect of Trump''s immigration policy who founded America First Legal and returned to the White House in 2025.', 'DC', 'Republican'),
('Peter Navarro', 'Other', 'Former White House Trade Advisor', 'Trump trade advisor who served prison time for contempt of Congress and remains active in MAGA politics.', 'CA', 'Republican'),
('Roger Severino', 'Other', 'Former HHS Civil Rights Director', 'Conservative policy figure who led the HHS Office for Civil Rights and is active in religious liberty advocacy.', 'DC', 'Republican'),
('Mike Lindell', 'Other', 'CEO of MyPillow', 'Businessman and prominent 2020 election conspiracy promoter who is a major Trump supporter.', 'MN', 'Republican'),
('Rudy Giuliani', 'Lawyer', 'Former Mayor of New York City', 'Former NYC mayor and Trump personal attorney who led efforts to challenge the 2020 election results.', 'NY', 'Republican'),
('Sidney Powell', 'Lawyer', 'Conservative Attorney', 'Attorney who promoted conspiracy theories about the 2020 election and pleaded guilty in the Georgia case.', 'TX', 'Republican'),
('Lin Wood', 'Lawyer', 'Conservative Attorney', 'Defamation attorney who became a prominent figure in the 2020 election challenge movement.', 'GA', 'Republican'),
('Laura Loomer', 'Other', 'Conservative Activist and Commentator', 'Controversial far-right activist and media personality who is a close Trump ally.', 'FL', 'Republican'),
('Ali Alexander', 'Other', 'Stop the Steal Organizer', 'Political activist who helped organize the Stop the Steal movement and January 6 rally.', 'TX', 'Republican'),
('Garrett Ziegler', 'Other', 'Founder of Marco Polo', 'Former Trump White House aide who founded Marco Polo to investigate Biden-related controversies.', 'DC', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- 13. TRUMP ORBIT (Family, Advisors, Allies)
-- ══════════════════════════════════════════════════════════════════
('Donald Trump Jr.', 'Other', 'Executive Vice President of The Trump Organization', 'Trump''s eldest son who is a prominent conservative media personality and political surrogate.', 'FL', 'Republican'),
('Eric Trump', 'Other', 'Executive Vice President of The Trump Organization', 'Trump''s son who manages Trump Organization operations and is active in Republican politics.', 'FL', 'Republican'),
('Ivanka Trump', 'Other', 'Former Senior White House Advisor', 'Trump''s daughter who served as a senior advisor in the first Trump administration.', 'FL', 'Republican'),
('Jared Kushner', 'Other', 'Former Senior White House Advisor', 'Trump''s son-in-law who served as a senior advisor handling Middle East policy and government modernization.', 'FL', 'Republican'),
('Robert F. Kennedy Jr.', 'Executive', 'Secretary of Health and Human Services', 'Former independent presidential candidate who endorsed Trump and became HHS Secretary.', 'CA', 'Republican'),
('Tulsi Gabbard', 'Executive', 'Director of National Intelligence', 'Former Democratic congresswoman who endorsed Trump and became Director of National Intelligence.', 'HI', 'Republican'),
('Pete Hegseth', 'Executive', 'Secretary of Defense', 'Former Fox News host who became Trump''s Secretary of Defense.', 'TN', 'Republican'),
('Russell Vought', 'Executive', 'Director of the Office of Management and Budget', 'Conservative policy architect who led Project 2025 planning and returned as OMB Director.', 'VA', 'Republican'),
('John Ratcliffe', 'Executive', 'Director of the CIA', 'Former Texas congressman who served as DNI and became Trump''s CIA Director.', 'TX', 'Republican'),
('Pam Bondi', 'Executive', 'U.S. Attorney General', 'Former Florida Attorney General who became Trump''s Attorney General.', 'FL', 'Republican'),
('Tom Homan', 'Executive', 'Border Czar', 'Former ICE Director who returned as Trump''s border czar to lead immigration enforcement.', 'DC', 'Republican'),
('Scott Bessent', 'Executive', 'Secretary of the Treasury', 'Hedge fund manager who became Trump''s Treasury Secretary.', 'SC', 'Republican'),
('Lee Zeldin', 'Executive', 'Administrator of the EPA', 'Former New York congressman who became Trump''s EPA Administrator.', 'NY', 'Republican'),
('Linda McMahon', 'Executive', 'Secretary of Education', 'Former WWE executive and SBA Administrator who became Trump''s Education Secretary.', 'CT', 'Republican'),
('Howard Lutnick', 'Executive', 'Secretary of Commerce', 'CEO of Cantor Fitzgerald who became Trump''s Commerce Secretary.', 'NY', 'Republican'),
('Hope Hicks', 'Strategist', 'Former White House Communications Director', 'Longtime Trump communications advisor who served in senior White House roles.', 'NY', 'Republican'),
('Dan Scavino', 'Strategist', 'Former White House Deputy Chief of Staff for Communications', 'Trump''s longest-serving aide who managed his social media strategy.', 'NY', 'Republican'),
('Mark Meadows', 'Other', 'Former White House Chief of Staff', 'Former congressman and Trump''s last chief of staff in the first term who faced legal scrutiny over January 6.', 'NC', 'Republican'),
('John McEntee', 'Other', 'Former Director of White House Presidential Personnel Office', 'Trump loyalist who led personnel vetting and was involved in Heritage Foundation''s Project 2025.', 'DC', 'Republican'),
('Richard Grenell', 'Strategist', 'Former Acting Director of National Intelligence', 'Former Ambassador to Germany and acting DNI who is a prominent Trump ally and advisor.', 'CA', 'Republican'),
('Keith Kellogg', 'Executive', 'Special Envoy to Ukraine and Russia', 'Retired Army general serving as Trump''s special envoy for the Ukraine-Russia conflict.', 'DC', 'Republican'),
('Robert O''Brien', 'Other', 'Former National Security Advisor', 'Trump''s fourth National Security Advisor who is considered a future GOP foreign policy leader.', 'CA', 'Republican'),

-- ══════════════════════════════════════════════════════════════════
-- ADDITIONAL NOTABLE FIGURES
-- ══════════════════════════════════════════════════════════════════
('Newt Gingrich', 'Strategist', 'Former Speaker of the House', 'Former House Speaker who led the Republican Revolution of 1994 and remains an influential conservative voice.', 'VA', 'Republican'),
('Rupert Murdoch', 'Donor', 'Founder of News Corp and Fox Corporation', 'Media mogul who built the Fox News empire and shaped conservative media for decades.', 'NY', 'Republican'),
('Lachlan Murdoch', 'Executive', 'Chairman and CEO of Fox Corporation', 'Rupert Murdoch''s son who leads Fox Corporation and oversees Fox News operations.', 'NY', 'Republican'),
('Chris Ruddy', 'Executive', 'CEO of Newsmax', 'Founder and CEO of Newsmax who is a longtime personal friend of Donald Trump.', 'FL', 'Republican'),
('Salem Abraham', 'Donor', 'Conservative Media Investor', 'Investor in conservative media properties who supports Republican causes.', 'TX', 'Republican'),
('Phil Anschutz', 'Donor', 'Chairman of Anschutz Corporation', 'Billionaire businessman who owns The Washington Examiner and funds conservative causes.', 'CO', 'Republican'),
('Ben Carson', 'Other', 'Former Secretary of HUD', 'Retired neurosurgeon who served as Trump''s HUD Secretary and ran for president in 2016.', 'FL', 'Republican'),
('Jim DeMint', 'Other', 'Former U.S. Senator and Heritage President', 'Former senator who became Heritage Foundation president and helped shape the Tea Party movement.', 'SC', 'Republican'),
('Ted Olson', 'Lawyer', 'Former U.S. Solicitor General', 'Prominent conservative Supreme Court litigator who served as Solicitor General under George W. Bush.', 'DC', 'Republican'),
('Pat Cipollone', 'Lawyer', 'Former White House Counsel', 'Trump''s White House Counsel who testified before the January 6 Committee.', 'DC', 'Republican'),
('Scott Walker', 'Other', 'President of Young America''s Foundation', 'Former Wisconsin governor and presidential candidate who now leads Young America''s Foundation.', 'WI', 'Republican'),
('Jim Banks', 'Elected Official', 'U.S. Senator from Indiana', 'Conservative congressman elected to the Senate in 2024 and founder of the Republican Study Committee.', 'IN', 'Republican'),
('Mike Gallagher', 'Other', 'Former U.S. Representative from Wisconsin', 'Former congressman who chaired the Select Committee on the CCP before leaving office.', 'WI', 'Republican'),
('Devin Nunes', 'Executive', 'CEO of Truth Social / Trump Media', 'Former congressman who now runs Trump Media & Technology Group and Truth Social.', 'CA', 'Republican'),
('Harmeet Dhillon', 'Lawyer', 'Republican National Committeewoman from California', 'Conservative attorney and RNC committeewoman who challenged Ronna McDaniel for RNC chair.', 'CA', 'Republican'),
('Mark Robinson', 'Candidate', 'Former Candidate for Governor of North Carolina', 'Former North Carolina Lieutenant Governor who was the 2024 Republican gubernatorial nominee.', 'NC', 'Republican'),
('Kari Lake', 'Candidate', 'Former Candidate for U.S. Senate from Arizona', 'Former TV anchor and MAGA candidate who ran for governor and Senate in Arizona.', 'AZ', 'Republican'),
('Tudor Dixon', 'Candidate', 'Former Candidate for Governor of Michigan', 'Conservative media personality who was the 2022 Republican nominee for governor of Michigan.', 'MI', 'Republican'),
('Blake Masters', 'Candidate', 'Former Candidate for U.S. Senate from Arizona', 'Peter Thiel protege who ran for Senate in Arizona and serves in conservative policy circles.', 'AZ', 'Republican'),
('Herschel Walker', 'Candidate', 'Former Candidate for U.S. Senate from Georgia', 'Football legend and Trump ally who was the 2022 Republican Senate nominee in Georgia.', 'GA', 'Republican'),
('Doug Mastriano', 'Elected Official', 'Pennsylvania State Senator', 'Pennsylvania state senator and 2022 GOP gubernatorial nominee known for election integrity activism.', 'PA', 'Republican'),
('Ken Paxton', 'Elected Official', 'Attorney General of Texas', 'Texas AG who survived impeachment and leads major conservative legal challenges against the federal government.', 'TX', 'Republican'),
('Andrew Bailey', 'Elected Official', 'Attorney General of Missouri', 'Missouri AG who has filed numerous lawsuits challenging Biden administration policies.', 'MO', 'Republican'),
('Dave Rubin', 'Media Figure', 'Host of The Rubin Report', 'Former progressive commentator who became a prominent conservative media figure and free speech advocate.', 'FL', 'Republican'),
('Tomi Lahren', 'Media Figure', 'Conservative Commentator at Outkick', 'Young conservative media personality known for viral commentary videos.', 'TN', 'Republican'),
('Kayleigh McEnany', 'Media Figure', 'Co-host of Outnumbered on Fox News', 'Former Trump White House Press Secretary who became a Fox News host.', 'FL', 'Republican'),
('Sarah Palin', 'Other', 'Former Governor of Alaska', 'Former Alaska governor and 2008 VP nominee who helped pave the way for populist conservatism.', 'AK', 'Republican'),
('Jessica Anderson', 'Executive', 'Executive Director of Heritage Action', 'Leader of Heritage Action who pushes conservative legislative priorities on Capitol Hill.', 'DC', 'Republican'),
('David McIntosh', 'Executive', 'Former President of Club for Growth', 'Former Indiana congressman who led Club for Growth into a major force in Republican primaries.', 'IN', 'Republican'),
('Ed Gillespie', 'Strategist', 'Former RNC Chairman', 'Former RNC chairman, White House counselor to George W. Bush, and Virginia gubernatorial candidate.', 'VA', 'Republican'),
('Sean Spicer', 'Media Figure', 'Former White House Press Secretary', 'Trump''s first press secretary who became a conservative media personality on Newsmax.', 'VA', 'Republican'),
('Hogan Gidley', 'Strategist', 'Former Trump White House Deputy Press Secretary', 'Republican communications operative who served in the Trump White House.', 'DC', 'Republican'),
('Mercedes Schlapp', 'Strategist', 'Former White House Director of Strategic Communications', 'Conservative commentator and Republican strategist married to Matt Schlapp.', 'VA', 'Republican'),
('Larry Kudlow', 'Media Figure', 'Host of Kudlow on Fox Business', 'Former Trump National Economic Council Director who hosts a show on Fox Business.', 'CT', 'Republican'),
('Steve Mnuchin', 'Other', 'Former Secretary of the Treasury', 'Former Goldman Sachs executive and film financier who served as Trump''s first Treasury Secretary.', 'CA', 'Republican'),
('Wilbur Ross', 'Other', 'Former Secretary of Commerce', 'Billionaire investor who served as Trump''s Commerce Secretary.', 'FL', 'Republican'),
('Robert Lighthizer', 'Other', 'Former U.S. Trade Representative', 'Architect of Trump''s tariff and trade policies who shaped the economic nationalist agenda.', 'FL', 'Republican')

ON CONFLICT DO NOTHING;
